TheFoundryVisionmongers/flix-scripts

shotgun/docs/flix.html
shotgun/docs/flix_ui.html
shotgun/docs/main.html
shotgun/docs/shotgun_ui.html
shotgun/flix.py
shotgun/flix_ui.py
shotgun/main.py
shotgun/shotgun_ui.py

(Refactor)[Shotgun]: Refactor flix UI and shotgun script

---

hiero/docs/flix.html
hiero/docs/flix_ui.html
hiero/docs/hiero_c.html
hiero/docs/hiero_ui.html
hiero/docs/main.html
hiero/flix.py
hiero/flix_ui.py
hiero/hiero_c.py
hiero/hiero_ui.py
hiero/main.py

(Refactor)[Hiero]: Refactor flix UI and hiero script

---

hiero/flix.py
hiero/flix_ui.py
hiero/hiero_c.py
hiero/hiero_ui.py
hiero/main.py
shotgun/flix.py
shotgun/flix_ui.py
shotgun/main.py
shotgun/shotgun.py
shotgun/shotgun_ui.py

(Refactor)[Files]: Add copyright

---

license_management/README.md
license_management/flix.py
license_management/main.py
license_management/requirements.txt

[437218](Userstory) Add license management script

---

pdf/README.md
pdf/main.py
pdf/requirements.txt

Add missing library on pdf requirements.txt

[438997](Userstory) Add missing library on pdf requirements.txt

---

hiero/README.md
pdf/README.md
shotgun/README.md

Updated Readmes to explain how to re-generate documentation

[462331](Userstory) Add documentation about doc regeneration

---

dialogue_relink/README.md
dialogue_relink/flix.py
dialogue_relink/main.py
dialogue_relink/requirements.txt
license_management/requirements.txt

Created Python script to relink dialogues for panels

[472666][Support] Dialogue relink

---

flixpy/README.md
flixpy/examples/webhook_add.py
flixpy/flix/__init__.py
flixpy/flix/cli/interactive_client.py
flixpy/flix/cli/main.py
flixpy/flix/lib/client.py
flixpy/flix/lib/errors.py
flixpy/flix/lib/forms.py
flixpy/flix/lib/signing.py
flixpy/poetry.lock
flixpy/pyproject.toml

This PR adds an initial version of a CLI utility that allows you to manage webhooks, along with the library backing the utility and an example script showing how to use the library.

[develop][518221](Task) [S] Webhooks: create python script

---

flixpy/examples/webhook_add.py
flixpy/examples/webhook_server.py
flixpy/flix/__init__.py
flixpy/flix/cli/interactive_client.py
flixpy/flix/cli/main.py
flixpy/flix/lib/client.py
flixpy/flix/lib/forms.py
flixpy/flix/lib/models.py
flixpy/flix/lib/signing.py
flixpy/flix/lib/types.py
flixpy/flix/lib/webhooks.py
flixpy/poetry.lock
flixpy/pyproject.toml

* `flix webhook ping` command that lets you ping a selected webhook
* `flix webhook run_server` command that starts a test server that simply prints any incoming events to stdout
* Utilities for setting up webhook handlers, and an `examples/webhook_server.py` example showing how to use them

[develop][518350](Task) [S] Webhooks: Python server for demo

---

flixpy/flix/cli/main.py
flixpy/flix/lib/forms.py

* Print the correct default index when the default value of a choice input is present in the list of options
* Add help to webhook server command

[develop][518350](Task) small fixes to webhook commands

---

flixpy/flix/cli/main.py

Minor change to fix `flix curl` command since the client API was modified

[develop][517910](UserStory) fix flix curl command

---

flixpy/flix/cli/main.py
flixpy/flix/lib/forms.py
flixpy/flix/lib/models.py

* Add support for field requirements for forms
* Add commands for managing (adding, editing, listing, deleting, assigning to shows) contact sheets

[develop][520795](Task) [S] Add contact sheet management to Python CLI command

---

flixpy/flix/cli/main.py
flixpy/flix/lib/forms.py

* add logout command to make the cli utility easier to test with different accounts
* minor display fix to enum forms

[develop][521819](UserStory) [S] add logout command

---

flixpy/flix/cli/main.py
flixpy/flix/lib/models.py
flixpy/flix/lib/webhooks.py

Add models for new contact sheet created event

[develop][519114](UserStory) add contact sheet webhook event

---

flixpy/flix/__init__.py
flixpy/flix/cli/main.py
flixpy/flix/lib/client.py
flixpy/flix/lib/errors.py
flixpy/flix/lib/types.py
flixpy/flix/lib/websocket.py

Adds functions for importing AAFs, as well as websocket utilities for listening to chain updates

[develop][525853](UserStory) add aaf importing functionality

---

flixpy/flix/cli/main.py
flixpy/flix/lib/client.py
flixpy/flix/lib/types.py
flixpy/flix/lib/websocket.py

This PR makes it possible to export QuickTimes, contact sheets, dialogue and state YAML files the following using the Python SDK and the `flix` CLI command.

[develop][525850](UserStory) cli commands for exporting shows and sequence revisions

---

flixpy/flix/lib/models.py
flixpy/flix/lib/types.py

Adds support for reading and saving the viewport of keyframes

[develop][525857](UserStory) add keyframe viewport support

---

flixpy/flix/cli/main.py
flixpy/flix/lib/models.py
flixpy/flix/lib/types.py

* Update viewport model
* Add new flag for yaml exports

[develop][506699](Bug) update sdk with new viewport model and yaml export flag

---

flixpy/flix/lib/types.py

Fixes issue where an exception would be raised when attempting to update the local media object information after an upload in the case where we only have upload permissions, not download permissions

[develop][506699](Bug) fix exception when uploading media object without download permissions

---

move_shows/src/main.py

Changes:
- Handling moving sequences between episodic shows
- Handling moving a sequence to an empty show
- Under this circumstance the destination show will not have a show directory in the asset directory

[master][535763](Request) move show bug

---

flixpy/flix/extension/extension_api.yaml
flixpy/flix/extension/extension_api/models/__init__.py
flixpy/flix/extension/extension_api/models/extension_open_file_panel_data.py
flixpy/flix/extension/extension_api/models/open_source_file_data.py
flixpy/flix/extension/extension_api/models/source_file.py
flixpy/flix/extension/types.py

The main changes of this PR are:
- Update sourceFile property in yaml, types and generate api
- Add OpenSourceFileData type
The following manual steps were taken by the dev to ensure this change is working and has not broken other parts of the
application:
- None
These are the changes and updates to automated tests related to this change:
- None
The following tickets have been created to update or add E2E tests for this change:
- None
None
The following branches should receive a cherry-picked PR after this PR is merged:
- None

[master][558329](Bug) [Maya] Send to 3d button no longer working

---

flixpy/flix/extension/client.py
flixpy/flix/extension/extension_api.yaml
flixpy/flix/extension/extension_api/api/status/status_controller_get.py
flixpy/flix/extension/extension_api/models/__init__.py
flixpy/flix/extension/extension_api/models/actions_in_progress.py
flixpy/flix/extension/extension_api/models/extension_open_file_panel_data.py
flixpy/flix/extension/extension_api/models/open_source_file_event.py
flixpy/flix/extension/extension_api/models/revision_status.py
flixpy/flix/extension/extension_api/models/sequence_revision_details_dto.py
flixpy/flix/extension/extension_api/models/status.py
flixpy/flix/extension/extension_api/models/websocket_event.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_2.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_2_type.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_3.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_3_type.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_5.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_5_type.py
flixpy/flix/extension/extension_api/models/websocket_event_data_type_6.py
flixpy/flix/extension/types.py

* add status event and related types/methods
* automatically track current flix status
* add `Extension.status` convenience property which returns a single flag value representing the current status, including offline status and project status, which can be used by extensions to check if a panel can be sent, and if not, why

[master][549616](UserStory) Maya: Traffic light system notification

---

flixpy/flix/extension/client.py
flixpy/flix/extension/extension_api.yaml
flixpy/flix/extension/extension_api/models/panel_request.py
flixpy/flix/extension/extension_api/models/panel_request_source_file.py
flixpy/flix/extension/types.py

Update to send the origin as a root property of the panel request body

[master][553532](Bug) Panels from Maya have the origin set as Photoshop

---

flixpy/README.md
flixpy/pyproject.toml

Update README to clarify requirements

[main][568343](Bug) [PUBLIC] Flix SDK 2 docs should show Flix 7 or newer is required

---

flixpy/flix/cli/main.py
flixpy/flix/lib/types.py
flixpy/flix/lib/websocket.py

Adds SDK method and command to create a show archive.

[main][568972](Task) [S] Add SDK command for archiving a show

---

flixpy/examples/revision_a_panel.py
flixpy/examples/shotgrid_create_show.py
flixpy/examples/shotgrid_version_sequence.py
flixpy/flix/lib/models.py
flixpy/flix/lib/types.py

* handle hidden and autosave properties, colour tags, show state, panel dialogue
* add methods for fetching assignable colour tags, dialogue history
* touchups to make sdk a bit more ergonomic
* automatically save dialogue as needed
* add flag for automatically fetching sequence panels when fetching a sequence revision
* add property for reading and writing dialogue as a string
* add property for setting colour tags using the tag name
* add a few docstrings to document side effects

[main][579963](Task) [SDK] Update SDK with new dialogue model
